Improve ./aa script - add fp (file-push) action

diff --git a/aa b/aa
--- a/aa
+++ b/aa
@@ -36,24 +36,26 @@ usage() {
   echo	  "   -s DEV    Perform actions only on DEV (can give more than once)"
   echo	  "   -h, -?    Display this help and exit"
   echo	  "Actions:"
-  echo	  "   ps                         List all serval processes"
-  echo	  "   sh|shell [cmd args... ;]   Run shell command (interactive if no cmd)"
-  echo	  "   su|sudo cmd [args... ;]    Run shell command as superuser"
-  echo	  "   au|app-uninstall           Uninstall org.servalproject application"
-  echo	  "   ai|app-install             Install $APK"
-  echo	  "   aid|app-install-debug      Install $APK_DEBUG"
-  echo	  "   ar|app-reinstall           Reinstall $APK"
-  echo	  "   ard|app-reinstall-debug    Reinstall $APK_DEBUG"
-  echo	  "   as|app-start               Start org.servalproject application"
-  echo	  "   du|dna-unlock              Unlock dna binary (chmod a+x bin/dna; chmod a+rw var/hlr.dat"
-  echo	  "   dl|dna-lock                Lock dna binary (chmod go-x bin/dna; chmod go-rw var/hlr.dat"
-  echo	  "   dp|dna-push                Push dna binary, if no permission then unlock and retry"
-  echo	  "   dq|dna-query               Detect if dna is running (greps ps output)"
-  echo	  "   dk|dna-kill                Kill dna (if running)"
-  echo	  "   ds|dna-start [args... ;]   Run dna in foreground (if not running) with given args"
-  echo	  "   dd|dna-dump-hlr            Dump dna's HLR to stdout"
-  echo	  "   dna|dna-invoke [args... ;] Invoke dna with arguments"
-  echo	  "   lc|logcat [args... ;]      Run adb logcat with arguments"
+  echo	  "   ps                             List all serval processes"
+  echo	  "   sh|shell [cmd args... ;]       Run shell command (interactive if no cmd)"
+  echo	  "   su|sudo cmd [args... ;]        Run shell command as superuser"
+  echo	  "   au|app-uninstall               Uninstall org.servalproject application"
+  echo	  "   ai|app-install                 Install $APK"
+  echo	  "   aid|app-install-debug          Install $APK_DEBUG"
+  echo	  "   ar|app-reinstall               Reinstall $APK"
+  echo	  "   ard|app-reinstall-debug        Reinstall $APK_DEBUG"
+  echo	  "   as|app-start                   Start org.servalproject application"
+  echo	  "   du|dna-unlock                  Unlock dna binary (chmod a+x bin/dna; chmod a+rw var/hlr.dat"
+  echo	  "   dl|dna-lock                    Lock dna binary (chmod go-x bin/dna; chmod go-rw var/hlr.dat"
+  echo	  "   dp|dna-push                    Push dna binary, if no permission then unlock and retry"
+  echo	  "   dq|dna-query                   Detect if dna is running (greps ps output)"
+  echo	  "   dk|dna-kill                    Kill dna (if running)"
+  echo	  "   ds|dna-start [args... ;]       Run dna in foreground (if not running) with given args"
+  echo	  "   dd|dna-dump-hlr                Dump dna's HLR to stdout"
+  echo	  "   dna|dna-invoke [args... ;]     Invoke dna with arguments"
+  echo	  "   lc|logcat [args... ;]          Run adb logcat with arguments"
+  echo	  "   fp|file-push path dest [;]     Push single file"
+  echo	  "   fp|file-push path... dest/ [;] Push many files to single directory"
 }
 
 # The following functions implement actions.  Functions starting with underscore '_' are generally
@@ -190,6 +192,23 @@ logcat() {
   run adb -s $DEV logcat "$@"
 }
 
+file_push() {
+  local dstarg
+  eval dstarg="\$$#"
+  local i=1
+  local src
+  local dst
+  while [ $i -lt $# ]; do
+    eval src=\"\$$i\"
+    dst="$dstarg"
+    case "$dstarg" in
+    */) dst="$dstarg${src##*/}";;
+    esac
+    run adb -s $DEV push "$src" "$dst"
+    i=$(($i + 1))
+  done
+}
+
 # Add shell quotation to the given arguments, so that when expanded using 'eval', the exact same
 # argument results.  This makes our argument handling fully immune to spaces and shell
 # metacharacters.
@@ -271,33 +290,54 @@ shiftargs() {
   do
     actions="$actions `shellarg \"$1\"`"
     NARGS=$(($NARGS+1))
+    eval ARG$NARGS=\"\$1\"
+    LASTARG="$1"
     shift
   done
 }
 while [ $# -ne 0 ]
 do
-  case $1 in
+  action="$1"
+  shift
+  case $action in
   \; ) shift;;
-  sh | shell )		      shift; shiftargs 'shell' "$@"; shift $NARGS; [ $NARGS -eq 0 ] && interactive=true;;
-  su | sudo )		      shift; shiftargs 'shell_sudo' "$@"; shift $NARGS;;
-  ps )			      actions="$actions ; serval_processes"; shift;;
-  au | app-uninstall )	      actions="$actions ; app_uninstall"; shift;;
-  ai | app-install )	      actions="$actions ; app_install '$APK'"; shift;;
-  aid | app-install-debug )   actions="$actions ; app_install '$APK_DEBUG'"; shift;;
-  ar | app-reinstall )	      actions="$actions ; app_reinstall '$APK'"; shift;;
-  ard | app-reinstall-debug ) actions="$actions ; app_reinstall '$APK_DEBUG'"; shift;;
-  as | app-start )	      actions="$actions ; app_start"; shift;;
-  du | dna-unlock )	      actions="$actions ; dna_unlock"; shift;;
-  dl | dna-lock )	      actions="$actions ; dna_lock"; shift;;
-  dp | dna-push )	      actions="$actions ; dna_push"; shift;;
-  dq | dna-query )	      actions="$actions ; dna_query"; shift;;
-  dk | dna-kill )	      actions="$actions ; dna_kill"; shift;;
-  dna | dna-invoke )	      shift; shiftargs 'dna_invoke' "$@"; shift $NARGS;;
-  ds | dna-start )	      shift; shiftargs 'dna_start' "$@"; shift $NARGS;;
-  dd | dna-dump-hlr )	      actions="$actions ; dna_dump_hlr"; shift;;
-  lc | logcat )	              shift; shiftargs 'logcat' "$@"; shift $NARGS;;
+  sh | shell )		      shiftargs 'shell' "$@"; shift $NARGS; [ $NARGS -eq 0 ] && interactive=true;;
+  su | sudo )		      shiftargs 'shell_sudo' "$@"; shift $NARGS;;
+  ps )			      actions="$actions ; serval_processes";;
+  au | app-uninstall )	      actions="$actions ; app_uninstall";;
+  ai | app-install )	      actions="$actions ; app_install '$APK'";;
+  aid | app-install-debug )   actions="$actions ; app_install '$APK_DEBUG'";;
+  ar | app-reinstall )	      actions="$actions ; app_reinstall '$APK'";;
+  ard | app-reinstall-debug ) actions="$actions ; app_reinstall '$APK_DEBUG'";;
+  as | app-start )	      actions="$actions ; app_start";;
+  du | dna-unlock )	      actions="$actions ; dna_unlock";;
+  dl | dna-lock )	      actions="$actions ; dna_lock";;
+  dp | dna-push )	      actions="$actions ; dna_push";;
+  dq | dna-query )	      actions="$actions ; dna_query";;
+  dk | dna-kill )	      actions="$actions ; dna_kill";;
+  dna | dna-invoke )	      shiftargs 'dna_invoke' "$@"; shift $NARGS;;
+  ds | dna-start )	      shiftargs 'dna_start' "$@"; shift $NARGS;;
+  dd | dna-dump-hlr )	      actions="$actions ; dna_dump_hlr";;
+  lc | logcat )	              shiftargs 'logcat' "$@"; shift $NARGS;;
+  fp | file-push )
+    shiftargs 'file_push' "$@"
+    shift $NARGS
+    if [ $NARGS -lt 2 ]; then
+      echo "Action '$action' missing argument -- see ${0##*/} -h for help." >&2
+      exit 1
+    fi
+    if [ $NARGS -gt 2 ]; then
+      case "$LASTARG" in
+      */) ;;
+      *)
+        echo "Action '$action' last argument must be a directory and end in '/' -- see ${0##*/} -h for help." >&2
+        exit 1
+        ;;
+      esac
+    fi
+    ;;
   *)
-    echo "Unsupported action '$1' -- see ${0##*/} -h for help." >&2
+    echo "Unsupported action '$action' -- see ${0##*/} -h for help." >&2
     exit 1
     ;;
   esac
